### ISSUE TITLE
Error in 3d noise function

### ISSUE THREAD

**Issue by jlmakes** [davidguttman/perlin-simplex#1]
In the original Java implementation, the `dot` function is overloaded for 2, 3 and 4 dimensions. However, in Sean McCullough's port, he only includes the 2 dimensional implementation.

```js
SimplexNoise.prototype.dot = function(g, x, y) { 
    return g[0]*x + g[1]*y;
};
```

So for example [this line](https://github.com/davidguttman/perlin-simplex/blob/master/index.js#L158)...

```js
else { 
    t0 *= t0; 
    n0 = t0 * t0 * this.dot(this.grad3[gi0], x0, y0, z0); // <-- here
}
```

...is just passing the `z0` argument into the abyss. This happens a couple more times, but it should be a pretty painless to fix, but I also have some other ideas for ways to improve the library. Are you open to a new maintainer for this package? I can at least offer a PR to fix the 3d noise function.

**Comment by davidguttman** [comment]
Ahh, thanks for looking to this and catching it!

A PR would be great -- happy to add you to the repo and npm.
